#!/bin/bash

## Step 1: QC with FastQC

# Directory containing the raw data
export raw_data_dir="Manuela Data/220211_A00181_0425_BHVMJNDSX2"
ls "$raw_data_dir"

# Set Internal Field Separator (IFS) to newline to handle filenames with spaces
IFS=$'\n'

# Find all .fastq files in the raw_data directory and its subdirectories
fastq_files=($(find "$raw_data_dir" -type f \( -iname "*.fastq" -o -iname "*.fastq.gz" -o -iname "*.fq" -o -iname "*.fq.gz" \)))

# Write them to a file
printf "%s\n" "${fastq_files[@]}" > fastq_files

# Output the number of files found
echo "Found ${#fastq_files[@]} FASTQ files."

# Submit the SLURM job array
num_files=${#fastq_files[@]}
echo "Submitting job array for $num_files files..."
sbatch --array=0-$(($num_files - 1)) git_repos/rnaseq_data_scripts/fastqc_array.sh


## Step 2: Trimming with Trimmomatic

# Set raw data directory
export raw_data_dir="temperature_samples/220211_A00181_0425_BHVMJNDSX2/"
ls "$raw_data_dir"

# Use newline separator
IFS=$'\n'

# Find all .fastq files in the raw_data directory and its subdirectories
fastq_files=($(find "$raw_data_dir" -type f \( -iname "*.fastq" -o -iname "*.fastq.gz" -o -iname "*.fq" -o -iname "*.fq.gz" \)))

# Output the number of files found
echo "Found ${#fastq_files[@]} FASTQ files."

# Find all paired .fastq files in the raw_data directory and its subdirectories

# Check for both R1 and R2 FASTQ files with updated pattern
R1_files=($(find "$raw_data_dir" -type f -name '*R1*.fastq.gz'))
R2_files=($(find "$raw_data_dir" -type f -name '*R2*.fastq.gz'))
num_files=${#R1_files[@]}

# Debugging: print R1 and R2 filenames found
echo "Number of R1 files: ${#R1_files[@]}"
echo "Number of R2 files: ${#R2_files[@]}"

# Submit the SLURM job array for paired files
num_files=${#R1_files[@]}
echo "Submitting job array for $num_files paired files..."
sbatch --array=0-$(($num_files - 1)) git_repos/rnaseq_data_scripts/trimmomatic_array.sh





