#!/bin/bash
#SBATCH -p short          # Partition name
#SBATCH -t 0-2:00         # Time limit (D-HH:MM)
#SBATCH -c 6              # Number of cores
#SBATCH --mem 6G          # Requested memory
#SBATCH -o %x_%j.out      # File to which stdout will be written
#SBATCH -e %x_%j.err      # File to which stderr will be written

# Load Salmon module if needed
# module load salmon

# Get variables passed via sbatch
salmon_index=$salmon_index
r1_file=$r1_file
r2_file=$r2_file
sample_name=$sample_name
output_dir=$output_dir

#run salmon (check how many threads I can allocate, here's 28)

echo "Processing sample ${base_filename}"
salmon quant -i "$salmon_index' -l A \
-1 "$r1_file" \
-2 "r2_file" \ 
-p 6
--validateMappings
-o "${output_dir}/${sample_name}_quant"

# Check if Salmon finished successfully
if [ $? -eq 0 ]; then
    echo "Salmon completed successfully for ${sample_name}."
else
    echo "Error: Salmon failed for ${sample_name}. Check logs for details."
    exit 1
fi

