#!/bin/bash
#SBATCH -p short          # Partition name
#SBATCH -t 0-2:00         # Time limit (D-HH:MM)
#SBATCH -c 6              # Number of cores
#SBATCH --mem 6G          # Requested memory
#SBATCH -o %x_%j.out      # File to which stdout will be written
#SBATCH -e %x_%j.err      # File to which stderr will be written

#Set path to salmon index
salmon_index = "salmon index file" 

#Trimmed fastq file folder
TRIM_DATA_DIR="trimmed data path"

#Loop through directories within the fastq folder (here SRR should be changed to whatever naming system my files will have)

for dir in ${TRIM_DATA_DIR}"/SRR*;do 

#Find R1 and R2 files
r1_file = $(find "$dir" -name"*_1.fastq.gz")
r2_file=$(find "$dir" -name"*_2.fastq.gz")

#Extract sample name
base_filename=$(basename "$dir")

#run salmon (check how many threads i can allocate, here's 28)
echo "Processing sample ${base_filename}"
salmon quant -i "$salmon_index' -l A \
-1 "$r1_file" \
-2 "r2_file" \ 
-p 28 --validateMappings -o "salmon_out/${samp}_quant"



