#!/bin/bash
#SBATCH -p short          # Partition name
#SBATCH -t 0-2:00         # Time limit (D-HH:MM)
#SBATCH -c 6              # Number of cores
#SBATCH --mem 6G          # Requested memory
#SBATCH -o %x_%j.out      # File to which stdout will be written
#SBATCH -e %x_%j.err      # File to which stderr will be written

# Load modules required for script commands
module load salmon
module load gzip

#Check files and directories are available

if [ ! -f "$transcriptome" ]; then
    echo "Error: Transcriptome file $transcriptome not found!"
    exit 1
fi

if [ ! -f "$decoy_file" ]; then
    echo "Error: Decoy file $decoy_file not found!"
    exit 1
fi

# Create the output directory for salmon index if it doesn't exist
mkdir -p $index_dir

# Run salmon index with the decoy-aware transcriptome
salmon index -t trans_and_gen.fa.gz -d decoys.txt -p 30 -i AGAM_PEST_salmon_index

# Check salmon indexing worked
if [ $? -eq 0 ]; then
    echo "Salmon index completed successfully in $elapsed_time seconds."
else
    echo "Error: Salmon index failed!"
    exit 1
fi


